basePath: /
definitions:
  models.CreateReservation:
    properties:
      end_time:
        type: string
      room_id:
        type: integer
      start_time:
        type: string
    required:
    - end_time
    - room_id
    - start_time
    type: object
  models.Reservation:
    properties:
      end_time:
        type: string
      id:
        type: integer
      room_id:
        type: integer
      start_time:
        type: string
    required:
    - end_time
    - room_id
    - start_time
    type: object
host: localhost:8443
info:
  contact: {}
  description: API server for Reservation application
  title: Reservation App
paths:
  /reservations:
    post:
      parameters:
      - description: reservation
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CreateReservation'
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: make reservation
      tags:
      - reservations
  /reservations/{room_id}:
    get:
      parameters:
      - description: Room ID
        in: path
        name: room_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Reservation'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Get all reservations for a room
      tags:
      - reservations
swagger: "2.0"
